### ISSUE TITLE
NameError: name 'zklib' is not defined

### ISSUE THREAD

**Issue by duybq86** [CybroOdoo/OpenHRMS#1]
Traceback (most recent call last):
  File "/mnt/d/Desktop/Odoo/V11/server/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/mnt/d/Desktop/Odoo/V11/server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/mnt/d/Desktop/Odoo/V11/server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/mnt/d/Desktop/Odoo/V11/server/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/mnt/d/Desktop/Odoo/V11/server/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/mnt/d/Desktop/Odoo/V11/server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/mnt/d/Desktop/Odoo/V11/server/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/mnt/d/Desktop/Odoo/V11/server/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/mnt/d/Desktop/Odoo/V11/server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/mnt/d/Desktop/Odoo/V11/server/addons/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/mnt/d/Desktop/Odoo/V11/server/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/mnt/d/Desktop/Odoo/V11/server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/mnt/d/Desktop/Odoo/V11/server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/mnt/d/Desktop/Odoo/V11/addons/oh_hr_zk_attendance/models/zk_machine.py", line 162, in download_attendance
    att_obj = self.env['hr.attendance']
NameError: name 'zklib' is not defined

**Comment by CybroOdoo** [comment]
Thanks for reaching out,
We will check and update the issue

**Comment by digitalliuzg** [comment]
Traceback (most recent call last):
  File "I:\greenodoo10-win_v2\odoo10\odoo\http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "I:\greenodoo10-win_v2\odoo10\odoo\http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "I:\greenodoo10-win_v2\odoo10\odoo\http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "I:\greenodoo10-win_v2\odoo10\odoo\service\model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "I:\greenodoo10-win_v2\odoo10\odoo\http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "I:\greenodoo10-win_v2\odoo10\odoo\http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "I:\greenodoo10-win_v2\odoo10\odoo\http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "I:\greenodoo10-win_v2\odoo10\addons\web\controllers\main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "I:\greenodoo10-win_v2\odoo10\addons\web\controllers\main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "I:\greenodoo10-win_v2\odoo10\odoo\api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "I:\greenodoo10-win_v2\odoo10\odoo\api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "I:\greenodoo10-win_v2\odoo10\odoo\addons\base\module\module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "I:\greenodoo10-win_v2\odoo10\odoo\addons\base\module\module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "I:\greenodoo10-win_v2\odoo10\odoo\modules\registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "I:\greenodoo10-win_v2\odoo10\odoo\modules\loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "I:\greenodoo10-win_v2\odoo10\odoo\modules\loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "I:\greenodoo10-win_v2\odoo10\odoo\modules\loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "I:\greenodoo10-win_v2\odoo10\odoo\modules\loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "I:\greenodoo10-win_v2\ocaaddons\stock_scanner\load_scenario.py", line 233, in scenario_convert_file
    kind=kind, report=report, pathname=pathname)
  File "I:\greenodoo10-win_v2\odoo10\odoo\tools\convert.py", line 839, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "I:\greenodoo10-win_v2\odoo10\odoo\tools\convert.py", line 895, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading oh_hr_lawsuit_management failed: file oh_hr_lawsuit_management\security/ir.model.access.csv could not be processed:
 No matching record found for external id 'model_case_details' in field 'Object'
Missing required value for the field 'Object' (model_id)
No matching record found for external id 'model_wizard_lawsuit' in field 'Object'
Missing required value for the field 'Object' (model_id)

**Comment by CybroOdoo** [comment]
The issue is already sorted out. Check with the latest code.
