### ISSUE TITLE
Odoo 12 CE - Saudi GOSI Error in installation

### ISSUE THREAD

**Issue by wshamasneh** [CybroOdoo/OpenHRMS#10]
While installing Saudi GOSI on Odoo 12 CE with sample data the following error is show up

Error:
Odoo Server Error

Traceback (most recent call last):
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\tools\convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\tools\convert.py", line 612, in _tag_record
    raise Exception("Cannot update missing record %r" % xid)
Exception: Cannot update missing record 'hr_payroll.structure_base1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 938, in __call__
    return self.method(*args, **kw)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\addons\web\controllers\main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\addons\web\controllers\main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\addons\base\models\ir_module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\addons\base\models\ir_module.py", line 442, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\addons\base\models\ir_module.py", line 535, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\modules\registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\modules\loading.py", line 426, in load_modules
    loaded_modules, update_module, models_to_check)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\modules\loading.py", line 318, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\modules\loading.py", line 224, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\modules\loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\tools\convert.py", line 801, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\tools\convert.py", line 864, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\tools\convert.py", line 754, in parse
    self.parse(rec, mode)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\tools\convert.py", line 763, in parse
    exc_info[2]
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\tools\pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\tools\convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\tools\convert.py", line 612, in _tag_record
    raise Exception("Cannot update missing record %r" % xid)
odoo.tools.convert.ParseError: "Cannot update missing record 'hr_payroll.structure_base1'" while parsing file:/d:/program%20files%20(x86)/odoo%2012.0/server/odoo/addons/saudi_gosi/data/rule.xml:48, near
<record id="hr_payroll.structure_base1" model="hr.payroll.structure">
            <field name="code">BASE</field>
            <field name="name">Base Salary Structure For Overseas Workers</field>
            <field eval="[(6, 0, [ref('hr_payroll.hr_rule_basic'),ref('hr_payroll.hr_rule_net')             ,ref('hr_payroll.hr_rule_taxable')])]" name="rule_ids"/>
            <field name="company_id" ref="base.main_company"/>
        </record>

**Comment by wshamasneh** [comment]
Odoo Server Error
Traceback (most recent call last):
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\tools\convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\tools\convert.py", line 612, in _tag_record
    raise Exception("Cannot update missing record %r" % xid)
Exception: Cannot update missing record 'hr_payroll.structure_base1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 938, in __call__
    return self.method(*args, **kw)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\addons\web\controllers\main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\addons\web\controllers\main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\addons\base\models\ir_module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\addons\base\models\ir_module.py", line 442, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\addons\base\models\ir_module.py", line 535, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\modules\registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\modules\loading.py", line 426, in load_modules
    loaded_modules, update_module, models_to_check)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\modules\loading.py", line 318, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\modules\loading.py", line 224, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\modules\loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\tools\convert.py", line 801, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\tools\convert.py", line 864, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\tools\convert.py", line 754, in parse
    self.parse(rec, mode)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\tools\convert.py", line 763, in parse
    exc_info[2]
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\tools\pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\tools\convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\tools\convert.py", line 612, in _tag_record
    raise Exception("Cannot update missing record %r" % xid)
odoo.tools.convert.ParseError: "Cannot update missing record 'hr_payroll.structure_base1'" while parsing file:/d:/program%20files%20(x86)/odoo%2012.0/server/odoo/addons/saudi_gosi/data/rule.xml:48, near
<record id="hr_payroll.structure_base1" model="hr.payroll.structure">
            <field name="code">BASE</field>
            <field name="name">Base Salary Structure For Overseas Workers</field>
            <field eval="[(6, 0, [ref('hr_payroll.hr_rule_basic'),ref('hr_payroll.hr_rule_net')             ,ref('hr_payroll.hr_rule_taxable')])]" name="rule_ids"/>
            <field name="company_id" ref="base.main_company"/>
        </record>

**Comment by CybroOdoo** [comment]
Fixed
