### ISSUE TITLE
Fresh Installation Error

### ISSUE THREAD

**Issue by khalloda** [CybroOdoo/OpenHRMS#12]
Odoo version: 12.0-20181015
OpenHRMS: Latest on this gethub for v12

error:
"
Uncaught Error: QWeb2: Template 'reminder_menu' not found
http://erp:8069/web/content/331-cb33ed7/web.assets_common.js:3374
Traceback:
Error: QWeb2: Template 'reminder_menu' not found
    at Object.exception (http://erp:8069/web/content/331-cb33ed7/web.assets_common.js:3374:7)
    at Engine._render (http://erp:8069/web/content/331-cb33ed7/web.assets_common.js:3419:103)
    at Engine.render (http://erp:8069/web/content/331-cb33ed7/web.assets_common.js:3415:151)
    at Class.renderElement (http://erp:8069/web/content/331-cb33ed7/web.assets_common.js:3672:1014)
    at http://erp:8069/web/content/331-cb33ed7/web.assets_common.js:3682:6
    at http://erp:8069/web/content/331-cb33ed7/web.assets_common.js:802:681
    at fire (http://erp:8069/web/content/331-cb33ed7/web.assets_common.js:796:299)
    at Object.add [as done] (http://erp:8069/web/content/331-cb33ed7/web.assets_common.js:797:467)
    at Array.<anonymous> (http://erp:8069/web/content/331-cb33ed7/web.assets_common.js:802:649)
    at Function.each (http://erp:8069/web/content/331-cb33ed7/web.assets_common.js:625:767)
"

**Comment by khalloda** [comment]
Gone after server restart
