### ISSUE TITLE
OpenHRMS shows error QWeb2: Template 'hr_reminder.reminder_menu' not found

### ISSUE THREAD

**Issue by djchavex** [CybroOdoo/OpenHRMS#22]
New instalation of Odoo 11 CE and OpenHRMS shows this error 

Erro:
Uncaught Error: QWeb2: Template 'hr_reminder.reminder_menu' not found

http://192.168.33.147:8069/web/content/425-120360c/web.assets_common.js:3689
Traceabilidade:
Error: QWeb2: Template 'hr_reminder.reminder_menu' not found
    at Object.exception (http://192.168.33.147:8069/web/content/425-120360c/web.assets_common.js:3689:7)
    at Engine._render (http://192.168.33.147:8069/web/content/425-120360c/web.assets_common.js:3734:103)
    at Engine.render (http://192.168.33.147:8069/web/content/425-120360c/web.assets_common.js:3730:151)
    at Class.renderElement (http://192.168.33.147:8069/web/content/425-120360c/web.assets_common.js:3949:1078)
    at http://192.168.33.147:8069/web/content/425-120360c/web.assets_common.js:3949:917
    at http://192.168.33.147:8069/web/content/425-120360c/web.assets_common.js:802:681
    at fire (http://192.168.33.147:8069/web/content/425-120360c/web.assets_common.js:796:299)
    at Object.add [as done] (http://192.168.33.147:8069/web/content/425-120360c/web.assets_common.js:797:467)
    at Array.<anonymous> (http://192.168.33.147:8069/web/content/425-120360c/web.assets_common.js:802:649)
    at Function.each (http://192.168.33.147:8069/web/content/425-120360c/web.assets_common.js:625:767)

can you help me please?

Best Regards

**Comment by stevanusyang** [comment]
New instalation of Odoo 11 CE and OpenHRMS error QWeb2: Template 'hr_reminder.reminder_menu' not found

I try to reboot my server (ubuntu 16.04), error not show, i can login but odoo page show nothing, icon is not show also.

please help,

Best Regards,
Stevanus

**Comment by patcadelina** [comment]
Happens on Odoo 12 as well. Error thrown after login: `Error: QWeb2: Template 'reminder_menu' not found`

Environment:
Ubuntu 18 LTS
Odoo Docker (odoo:latest)

**Comment by CybroOdoo** [comment]
Hi
We can't reproduce the issue.
Make sure that you have the updated version of odoo.

**Comment by ahmedehammad** [comment]
i have same issue in a clean odoo 12 installation , it shows 'reminder_menu' not found please advice

**Comment by huytl81** [comment]
i have same issue in a clean odoo 12 installation
