### ISSUE TITLE
[12.0] Saudi gosi issue during the payslip generation

### ISSUE THREAD

**Issue by muhammadfaizalns** [CybroOdoo/OpenHRMS#24]
Getting an error like this while creating payslip batches after installing the saudi_gosi module.

```
Odoo Server Error
Traceback (most recent call last):
  File "/home/faizal/odoo/odoo12/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/faizal/odoo/odoo12/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/faizal/odoo/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/faizal/odoo/odoo12/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/home/faizal/odoo/odoo12/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/faizal/odoo/odoo12/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/faizal/odoo/odoo12/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/faizal/odoo/odoo12/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/home/faizal/odoo/odoo12/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/faizal/odoo/odoo12/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/faizal/odoo/odoo12/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/faizal/odoo/odoo12/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/faizal/odoo/odoo12/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/faizal/odoo/odoo12/odoo/addons/hr_payroll_account/wizard/hr_payroll_payslips_by_employees.py", line 14, in compute_sheet
    return super(HrPayslipEmployees, self.with_context(journal_id=journal_id)).compute_sheet()
  File "/home/faizal/odoo/odoo12/odoo/addons/hr_payroll/wizard/hr_payroll_payslips_by_employees.py", line 26, in compute_sheet
    slip_data = self.env['hr.payslip'].onchange_employee_id(from_date, to_date, employee.id, contract_id=False)
TypeError: onchange_employee_id() got an unexpected keyword argument 'contract_id'
```

**Comment by CybroOdoo** [comment]
Hi
The issue is fixed.
