### ISSUE TITLE
Applying May 8th's patch breaks human resource module

### ISSUE THREAD

**Issue by beke** [CybroOdoo/OpenHRMS#27]
It seems last patch deleted or renamed a column in database, when applying it, human resource module will give "view n/a" error.
Upgrading the hrms core module will fix the issue but it will mess up the menu, attendance, report etc. will show up on main menu instead.

**Comment by CybroOdoo** [comment]
Could you please provide more details about the error?

**Comment by beke** [comment]
When I applied the Bug fix patch from 2 days and restarted the odoo service, I got the following error when trying to acces Human Resource module :
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 745, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 718, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/models.py", line 1376, in load_views
    for [v_id, v_type] in views
  File "/opt/odoo/odoo/odoo/models.py", line 1376, in <dictcomp>
    for [v_id, v_type] in views
  File "/opt/odoo/odoo/addons/mail/models/mail_thread.py", line 410, in fields_view_get
    res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/opt/odoo/odoo/odoo/models.py", line 1462, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 1084, in postprocess_and_fields
    fields_def = self.postprocess(model, node, view_id, False, fields)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 909, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 909, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 909, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  [Previous line repeated 5 more times]
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 869, in postprocess
    ).postprocess_and_fields(field.comodel_name, f, view_id)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 1063, in postprocess_and_fields
    self.raise_view_error(_('Model not found: %(model)s') % dict(model=model), view_id)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 548, in raise_view_error
    raise ValueError(message)
ValueError: Model not found: None

Error context:
View `n/a`
[view_id: n/a, xml_id: n/a, model: n/a, parent_id: n/a]

**Comment by beke** [comment]
And after I got the error, I tried upgrading the "Open HRMS employee info" module. After the upgrade I can access the "human resource" module but the main menu on the left was broken, meaning there was lot menu options that weren't there before, such as "Leaves config", "Settings", "Reports", "Payroll", "Expenses" etc.
