### ISSUE TITLE
Error while creating Exit Checklist

### ISSUE THREAD

**Issue by haninada** [CybroOdoo/OpenHRMS#35]
odoo 12 CE 

when creating a new Exit Checklist
I got the following error:
Uncaught TypeError: Widget is not a constructor
http://93.104.209.238:8069/web/content/448-92cbf9d/web.assets_backend.js:1577
Traceback:
TypeError: Widget is not a constructor
    at Class._renderFieldWidget (http://93.104.209.238:8069/web/content/448-92cbf9d/web.assets_backend.js:1577:308)
    at Class._renderInnerGroupField (http://93.104.209.238:8069/web/content/448-92cbf9d/web.assets_backend.js:1628:382)
    at http://93.104.209.238:8069/web/content/448-92cbf9d/web.assets_backend.js:1626:44
    at Function._.each._.forEach (http://93.104.209.238:8069/web/content/337-c8373c1/web.assets_common.js:12:558)
    at Class._renderInnerGroup (http://93.104.209.238:8069/web/content/448-92cbf9d/web.assets_backend.js:1623:63)
    at Class._renderTagGroup (http://93.104.209.238:8069/web/content/448-92cbf9d/web.assets_backend.js:1637:228)
    at Class._renderNode [as _super] (http://93.104.209.238:8069/web/content/448-92cbf9d/web.assets_backend.js:1629:246)
    at Class._renderNode (http://93.104.209.238:8069/web/content/448-92cbf9d/web.assets_backend.js:2818:50)
    at Class._renderNode (http://93.104.209.238:8069/web/content/337-c8373c1/web.assets_common.js:3541:371)
    at Function._.map._.collect (http://93.104.209.238:8069/web/content/337-c8373c1/web.assets_common.js:13:270)

Any advice

**Comment by CybroOdoo** [comment]
Hi
The issue is fixed , please download the updated version from odoo app store.

**Comment by haninada** [comment]
Thank you
