### ISSUE TITLE
Error during ohrms_core module installation

### ISSUE THREAD

**Issue by herr-fabs** [CybroOdoo/OpenHRMS#43]
I get this error during installation from the ohrms_core module. Branch 13

Are there any solutions?

`Fehler:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 713, in parse
    self._tag_root(de)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 675, in _tag_root
    f(rec)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 578, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 4005, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 3919, in _load_records_create
    return self.create(values)
  File "<decorator-gen-36>", line 2, in create
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 359, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_actions.py", line 235, in create
    return super(IrActionsActWindow, self).create(vals_list)
  File "<decorator-gen-34>", line 2, in create
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 359, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_actions.py", line 59, in create
    res = super(IrActions, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 359, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 3624, in create
    raise ValueError("Invalid field %r on model %r" % (key, self._name))
ValueError: Invalid field 'view_type' on model 'ir.actions.act_window'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\pycompat.py", line 14, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\web\controllers\main.py", line 1323, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\web\controllers\main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 410, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 397, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-58>", line 2, in button_immediate_install
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\loading.py", line 420, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\loading.py", line 312, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 737, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 804, in convert_xml_import
    obj.parse(doc.getroot())
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 722, in parse
    exc_info[2]
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 713, in parse
    self._tag_root(de)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 675, in _tag_root
    f(rec)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 578, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 4005, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 3919, in _load_records_create
    return self.create(values)
  File "<decorator-gen-36>", line 2, in create
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 359, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_actions.py", line 235, in create
    return super(IrActionsActWindow, self).create(vals_list)
  File "<decorator-gen-34>", line 2, in create
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 359, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_actions.py", line 59, in create
    res = super(IrActions, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 359, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 3624, in create
    raise ValueError("Invalid field %r on model %r" % (key, self._name))
odoo.tools.convert.ParseError: "Invalid field 'view_type' on model 'ir.actions.act_window'" while parsing file:/c:/program%20files%20(x86)/odoo%2013.0/server/odoo/addons/hr_contract_types/views/contract_view.xml:3, near
<odoo>
    <record id="hr_contract_form_view_inherit" model="ir.ui.view">
        <field name="name">hr.contract.view.form.inherit</field>
        <field name="model">hr.contract</field>
        <field name="inherit_id" ref="hr_contract.hr_contract_view_form"/>
        <field name="arch" type="xml">
            <xpath expr="//field[@name='job_id']" position="after">
                <field name="type_id"/>
            </xpath>
        </field>
    </record>

    <record id="hr_contract_type_view_form" model="ir.ui.view">
            <field name="name">hr.contract.type.form</field>
            <field name="model">hr.contract.type</field>
            <field name="arch" type="xml">
                <form string="Contract Type">
                    <group col="4">
                        <field colspan="4" name="name"/>
                    </group>
                </form>
            </field>
        </record>

        <record id="hr_contract_type_view_tree" model="ir.ui.view">
            <field name="name">hr.contract.type.tree</field>
            <field name="model">hr.contract.type</field>
            <field name="arch" type="xml">
                <tree string="Contract Type">
                    <field name="sequence" widget="handle"/>
                    <field colspan="4" name="name"/>
                </tree>
            </field>
        </record>

        <record id="hr_contract_type_view_search" model="ir.ui.view">
            <field name="name">hr.contract.type.search</field>
            <field name="model">hr.contract.type</field>
            <field name="arch" type="xml">
                <search string="Search Contract Type">
                    <field name="name" string="Contract Type"/>
                    <field name="sequence" string="Sequence"/>
               </search>
            </field>
        </record>

        <record id="action_hr_contract_type" model="ir.actions.act_window">
            <field name="name">Contract Types</field>
            <field name="res_model">hr.contract.type</field>
            <field name="view_type">form</field>
            <field name="view_mode">tree,form</field>
            <field name="search_view_id" ref="hr_contract_type_view_search"/>
        </record>

        <menuitem id="hr_menu_contract_type" action="action_hr_contract_type" parent="hr.menu_human_resources_configuration" sequence="3" groups="base.group_no_one"/>
</odoo>`

**Comment by CybroOdoo** [comment]
Hi,
The issue is fixed.
