### ISSUE TITLE
in loan approve 

### ISSUE THREAD

**Issue by walidalhawari** [CybroOdoo/OpenHRMS#47]
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo13/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo13/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo13/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo13/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1323, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo13/odoo-extra-addons/ohrms_loan_accounting/models/hr_loan_acc.py", line 121, in action_double_approve
    move = self.env['account.move'].create(vals)
  File "<decorator-gen-170>", line 2, in create
  File "/opt/odoo13/odoo/odoo/api.py", line 343, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo13/odoo/addons/account/models/account_move.py", line 1546, in create
    moves = super(AccountMove, self).create(vals_list)
  File "<decorator-gen-106>", line 2, in create
  File "/opt/odoo13/odoo/odoo/api.py", line 344, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo13/odoo/addons/mail/models/mail_thread.py", line 268, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo13/odoo/odoo/api.py", line 344, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo13/odoo/odoo/models.py", line 3722, in create
    records = self._create(data_list)
  File "/opt/odoo13/odoo/odoo/models.py", line 3862, in _create
    for other, data in zip(others, data_list)
  File "/opt/odoo13/odoo/odoo/fields.py", line 2740, in create
    self.write_batch(record_values, True)
  File "/opt/odoo13/odoo/odoo/fields.py", line 2766, in write_batch
    return self.write_real(records_commands_list, create)
  File "/opt/odoo13/odoo/odoo/fields.py", line 2930, in write_real
    flush()
  File "/opt/odoo13/odoo/odoo/fields.py", line 2894, in flush
    comodel.create(to_create)
  File "<decorator-gen-171>", line 2, in create
  File "/opt/odoo13/odoo/odoo/api.py", line 344, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo13/odoo/addons/account/models/account_move.py", line 3163, in create
    lines = super(AccountMoveLine, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo13/odoo/odoo/api.py", line 344, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo13/odoo/odoo/models.py", line 3679, in create
    raise ValueError("Invalid field %r on model %r" % (key, self._name))
ValueError: Invalid field 'loan_id' on model 'account.move.line'

**Comment by CybroOdoo** [comment]
Hi
We have fixed the issue, please get the updated version.

Thanks.
