### ISSUE TITLE
installation issue for Odoo12 Digital Ocean Ubuntu 19.04 

### ISSUE THREAD

**Issue by CaptAnil** [CybroOdoo/OpenHRMS#48]
Good day CybroOdoo Team ,
OpenHRMS Installation of this module causes the below odoo error log
Please resolve . 

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo12/odoo12-server/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo12/odoo12-server/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo12/odoo12-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo12/odoo12-server/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/odoo12/odoo12-server/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo12/odoo12-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo12/odoo12-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo12/odoo12-server/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/odoo12/odoo12-server/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/odoo12/odoo12-server/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo12/odoo12-server/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo12/odoo12-server/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/odoo12/odoo12-server/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/odoo12/odoo12-server/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo12/odoo12-server/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo12/odoo12-server/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo12/odoo12-server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo12/odoo12-server/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/odoo12/odoo12-server/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/odoo12/odoo12-server/odoo/modules/loading.py", line 194, in load_module_graph
    registry.setup_models(cr)
  File "/odoo12/odoo12-server/odoo/modules/registry.py", line 267, in setup_models
    model._setup_fields()
  File "/odoo12/odoo12-server/odoo/models.py", line 2627, in _setup_fields
    field.setup_full(self)
  File "/odoo12/odoo12-server/odoo/fields.py", line 502, in setup_full
    self._setup_regular_full(model)
  File "/odoo12/odoo12-server/odoo/fields.py", line 2428, in _setup_regular_full
    invf = comodel._fields[self.inverse_name]
KeyError: 'rating_id'

**Comment by CybroOdoo** [comment]
Hi
We can not reproduce the issue. For further support please sent a mail to odoo@cybrosys.com.

Thanks.
