### ISSUE TITLE
Error After Installing Open HRMS GOSI on Odoo 11 EE

### ISSUE THREAD

**Issue by wshamasneh** [CybroOdoo/OpenHRMS#5]
After installing Open HRMS GOSI on Odoo 11 EE with demo data, and error is raised up on select the Dashboard for the default employee on Open HRMS.
The error show as the following:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x0F2589F0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\hrms_dashboard\models\hrms_dashboard.py", line 33, in get_user_employee_details
    employee = self.env['hr.employee'].sudo().search_read([('user_id', '=', uid)], limit=1)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 4239, in search_read
    result = records.read(fields)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 2601, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 4758, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\fields.py", line 941, in __get__
    self.determine_value(record)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\fields.py", line 1052, in determine_value
    self.compute_value(recs)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\fields.py", line 1008, in compute_value
    self._compute_value(records)
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\fields.py", line 999, in _compute_value
    getattr(records, self.compute)()
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\addons\saudi_gosi\models\gosi.py", line 50, in compute_age
    self.ensure_one()
  File "D:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 4366, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: hr.employee(1, 9, 10, 11, 12)

**Comment by wshamasneh** [comment]
In addition the same Error shows up once select any defined employee.

**Comment by wshamasneh** [comment]
This issue in on Odoo 11 CE not EE.

**Comment by CybroOdoo** [comment]
Thanks for reaching out,
We will check and update.

**Comment by CybroOdoo** [comment]
@wshamasneh We have updated the Open HRMS GOSI. Please download the new code and check.
Thanks

**Comment by wshamasneh** [comment]
Dear Sir:

This issue has been resolved.

Thank you
