### ISSUE TITLE
Error when loading Dashboard and sharts don't work

### ISSUE THREAD

**Issue by soumayadg** [CybroOdoo/OpenHRMS#63]
Hello , 
I got this error when i loaded the dashboard , knowing that i m using V14 , the
![error](https://user-images.githubusercontent.com/47884751/99690077-03a50f80-2a88-11eb-8944-ac17b19d6f10.PNG)
 sharts didn't work (Monthly Leave Analysis , attrition rate .. ) , you will find joined an error also occured on the browser debugger tool .

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/openhrms/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/openhrms/odoo/http.py", line 682, in dispatch
    result = self._call_function(**self.params)
  File "/opt/openhrms/odoo/http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/openhrms/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/openhrms/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/openhrms/odoo/http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "/opt/openhrms/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/opt/openhrms/addons/web/controllers/main.py", line 1359, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/openhrms/addons/web/controllers/main.py", line 1351, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/openhrms/odoo/api.py", line 392, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/opt/openhrms/odoo/api.py", line 365, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/openhrms/openhrms/hrms_dashboard/models/hrms_dashboard.py", line 400, in get_attrition_rate
    list(filter(lambda d: d['l_month'] == month_emp[1].split(' ')[:1][0].strip()[:3], month_join))[0][
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/openhrms/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/openhrms/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
IndexError: list index out of range

**Comment by ericdai** [comment]
also same issue ,windows 10 Odoo 14 CE 
the dashboard module  report as below
Odoo Server Error
Traceback (most recent call last):
File "C:\o14\server\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
result = request.dispatch()
File "C:\o14\server\odoo\http.py", line 683, in dispatch
result = self._call_function(**self.params)
File "C:\o14\server\odoo\http.py", line 359, in _call_function
return checked_call(self.db, *args, **kwargs)
File "C:\o14\server\odoo\service\model.py", line 94, in wrapper
return f(dbname, *args, **kwargs)
File "C:\o14\server\odoo\http.py", line 347, in checked_call
result = self.endpoint(*a, **kw)
File "C:\o14\server\odoo\http.py", line 912, in __call__
return self.method(*args, **kw)
File "C:\o14\server\odoo\http.py", line 531, in response_wrap
response = f(*args, **kw)
File "C:\o14\server\odoo\addons\web\controllers\main.py", line 1377, in call_kw
return self._call_kw(model, method, args, kwargs)
File "C:\o14\server\odoo\addons\web\controllers\main.py", line 1369, in _call_kw
return call_kw(request.env[model], method, args, kwargs)
File "C:\o14\server\odoo\api.py", line 392, in call_kw
result = _call_kw_model(method, model, args, kwargs)
File "C:\o14\server\odoo\api.py", line 365, in _call_kw_model
result = method(recs, *args, **kwargs)
File "C:\o14\server\odoo\addons\hrms_dashboard\models\hrms_dashboard.py", line 404, in get_attrition_rate
match_join = list(filter(lambda  d['l_month'] == month_emp[1].split(' ')[:1][0].strip()[:3], month_join))[0]['count']
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "C:\o14\server\odoo\http.py", line 639, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "C:\o14\server\odoo\http.py", line 315, in _handle_exception
raise exception.with_traceback(None) from new_cause
IndexError: list index out of range
