### ISSUE TITLE
Error in View for current employee after install Open HRMS GOSI module in Odoo 12 ce with demo data

### ISSUE THREAD

**Issue by wshamasneh** [CybroOdoo/OpenHRMS#8]
Hi:

After installing Saudi GOSI module on Odoo 12 ce with sample data and once select any defined employee an error is raised up as the following:

Odoo Server Error
Traceback (most recent call last):
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 1032, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x08F7EE10>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\fields.py", line 970, in __get__
    value = record.env.cache.get(record, self)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 1034, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('hr.employee(1,).limit', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 938, in __call__
    return self.method(*args, **kw)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\addons\web\controllers\main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\addons\web\controllers\main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 2768, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 5042, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\fields.py", line 974, in __get__
    self.determine_value(record)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\fields.py", line 1085, in determine_value
    self.compute_value(recs)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\fields.py", line 1041, in compute_value
    self._compute_value(records)
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\fields.py", line 1032, in _compute_value
    getattr(records, self.compute)()
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\addons\saudi_gosi\models\gosi.py", line 50, in compute_age
    self.ensure_one()
  File "D:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 4643, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: hr.employee(1, 7, 9, 10, 11, 12)

**Comment by CybroOdoo** [comment]
@wshamasneh Thanks for reaching out,
We will check and update.

**Comment by CybroOdoo** [comment]
@wshamasneh We have updated the Open HRMS GOSI. Please download the new code and check.
Thanks

**Comment by wshamasneh** [comment]
The issue has been resolved and tested. Thank you
